name: Discord Notification

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: Intern.House GitHub Bot
        DISCORD_AVATAR: https://i.imgur.com/79bgPSZ.png
      uses: Ilshidur/action-discord@master
      with:
        args: '(Landing) A new commit has been pushed to master branch. '
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
